# Generated by Django 2.0.4 on 2018-04-19 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20180419_0800'),
    ]

    operations = [
        migrations.AddField(
            model_name='celda',
            name='size',
            field=models.IntegerField(default=100),
        ),
    ]
