# Generated by Django 2.0.4 on 2018-04-19 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_celda_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='civilizacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jugadores', to='game.Civilizacion'),
        ),
    ]
