# Generated by Django 2.0.4 on 2018-04-19 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20180419_0813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aldea',
            name='x',
        ),
        migrations.RemoveField(
            model_name='aldea',
            name='y',
        ),
        migrations.AddField(
            model_name='aldea',
            name='posicion',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='game.Celda'),
        ),
        migrations.AlterField(
            model_name='aldea',
            name='poblation',
            field=models.IntegerField(default=10),
        ),
    ]
