# Generated by Django 2.0.4 on 2018-04-17 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20180417_0340'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='nick',
            field=models.CharField(default='Test', max_length=50),
        ),
    ]
