# Generated by Django 2.0.4 on 2018-04-19 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20180419_0824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='celda',
            name='ocupada',
        ),
    ]
