# Generated by Django 2.0.4 on 2018-04-17 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_remove_jugador_nick'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mensajes',
            new_name='Mensaje',
        ),
    ]
