# Generated by Django 2.0.4 on 2018-04-18 19:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_auto_20180418_1916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jugador',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='jugador',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='aldea',
            name='jugador',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='emisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emisor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='receptor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receptor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Jugador',
        ),
    ]
