# Generated by Django 2.0.4 on 2018-04-18 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_auto_20180418_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='user',
            field=models.CharField(default='test', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jugador',
            name='civilizacion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='game.Civilizacion'),
        ),
    ]
